---
header-includes:
- \usepackage{xcolor}
- \usepackage{color} 
- \usepackage{fancyhdr,color}
- \usepackage{lipsum}
- \fancyfoot[CE] {\thepage}
title: "**Assignment 2\n &nbsp;  \n**"
subtitle: "Applied Forecasting in Complex Systems 2025"
author: João Bárbara (16228855)
date: "University of Amsterdam \n &nbsp;  \n November 23, 2025"
output: pdf_document
fontsize: 11pt
highlight: tango
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  dev.args = list(pointsize = 11)
)
options(digits = 3, width = 60)
library(fpp3)
library(patchwork)
library(fable)
library(tsibble)
library(dplyr)
library(tidyr)
library(data.table)
library(lubridate)
library(zoo)
library(matrixStats)
library(lightgbm)
library(ggplot2)
library(fabletools)
```

## **Exercise 1**\

\par \textbf{1.1.} After understanding how the \textit{tsibble} is organized, we can use \textit{filter()} to select the required data. In this case, \textit{State}, to find the information regarding the state of Victoria, \textit{Animal}, to find the data about pigs, and finally \textit{year(Month)}, since we have monthly data over multiple years, to find the data between 1990 and 1995.

```{r}
path_train <- "data/train_data.rds"
train_ts <- readRDS(path_train)
train_ts
```
```{r}
length(unique(train_ts$item_id))
```

```{r fig.width=12, fig.height=4, message=FALSE}
total_sales <- train_ts %>%
  index_by(date) %>%
  summarise(total_units = sum(units, na.rm = TRUE))

total_sales %>%
  autoplot(total_units) +
  ggtitle("Total Daily Sales (All Stores & Items)") +
  xlab("Date") + ylab("Total Units Sold") +
  theme_minimal()
```

```{r fig.width=12, fig.height=4, message=FALSE}
example_item_id <- train_ts$item_id[1]

# 2. Filter the data for just that item
single_item_data <- train_ts %>%
  filter(item_id == example_item_id)

# 3. Plot the specific item
single_item_data %>%
  autoplot(units) +
  ggtitle(paste("Daily Sales for Item:", example_item_id)) +
  xlab("Date") + ylab("Units Sold") +
  theme_minimal()
```
```{r fig.width=12, fig.height=4, message=FALSE}

lambda_total <- total_sales %>%
  features(total_units + 1, features = guerrero) %>%
  pull(lambda_guerrero)

print(paste("Optimal Lambda for Global Sales:", round(lambda_total, 3)))

total_sales %>%
  autoplot(box_cox(total_units + 1, lambda_total)) +
  ggtitle(paste0("Transformed Global Sales (Box-Cox, lambda = ", round(lambda_total, 2), ")")) +
  ylab("Transformed Units") +
  theme_minimal()

total_sales %>%
  model(
    STL(box_cox(total_units + 1, lambda_total) ~ season(period = 7) + season(period = 365.25),
    robust = TRUE)
  ) %>%
  components() %>%
  autoplot() +
  ggtitle("Decomposition of Global Sales (Transformed)")

```
